### ISSUE TITLE
Linux Build for Windows and Visual Studio 15

### ISSUE THREAD

**Issue by FloridaStream** [x-hgg-x/video_decrypter#2]
Can you add to Linux Build Script (exe for windows)? Because compile is too easy in linux.

I've also tried compiling following the information described here, but it's kind of confusing, and I think I made a mistake in the configuration.

A ready build for Visual Studio 15 would be very handy for compilation.

@x-hgg-x

**Comment by x-hgg-x** [comment]
There is some incompatibilty between Visual Studio and MinGW-w64. The sources here are only for compilation with MinGW-w64/gcc, because it is portable and a port to Linux is scheduled.
If you want to compile it with Visual Studio, you need to edit the sources and manually correct all the incompatibilties.
